"""sync_schema

Revision ID: be20c00ccbd6
Revises: 2b1d0735c307
Create Date: 2026-08-15 20:59:45.054313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be20c00ccbd6'
down_revision: Union[str, Sequence[str], None] = '2b1d0735c307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_call_scores_call_id'), table_name='call_scores')
    op.drop_table('call_scores')
    op.add_column('agents', sa.Column('team', sa.String(length=120), nullable=True))
    op.alter_column('agents', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('agents', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('agents', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=True)
    op.alter_column('agents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'agents', ['email'])
    op.drop_constraint(op.f('agents_org_id_fkey'), 'agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'organizations', ['org_id'], ['id'])
    op.add_column('background_tasks', sa.Column('org_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'background_tasks', 'organizations', ['org_id'], ['id'])
    op.add_column('calls', sa.Column('customer_ref', sa.String(length=120), nullable=True))
    op.add_column('calls', sa.Column('audio_path', sa.String(length=500), nullable=True))
    op.alter_column('calls', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('calls', 'call_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.drop_index(op.f('idx_calls_org_date'), table_name='calls')
    op.drop_constraint(op.f('calls_org_id_fkey'), 'calls', type_='foreignkey')
    op.drop_constraint(op.f('calls_agent_id_fkey'), 'calls', type_='foreignkey')
    op.create_foreign_key(None, 'calls', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'calls', 'organizations', ['org_id'], ['id'])
    op.drop_constraint(op.f('calls_status_check'), 'calls', type_='check')
    op.drop_column('calls', 'created_at')
    op.drop_column('calls', 'status')
    op.drop_column('calls', 'audio_url')
    op.add_column('mailbox_items', sa.Column('org_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'mailbox_items', 'organizations', ['org_id'], ['id'])
    op.alter_column('organizations', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('organizations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_check_constraint('check_compliance_score', 'qa_scores', 'compliance_score >= 0 AND compliance_score <= 100')
    op.create_check_constraint('check_greeting_score', 'qa_scores', 'greeting_score >= 0 AND greeting_score <= 100')
    op.create_check_constraint('check_overall_score', 'qa_scores', 'overall_score >= 0 AND overall_score <= 100')
    op.create_check_constraint('check_resolution_score', 'qa_scores', 'resolution_score >= 0 AND resolution_score <= 100')
    op.create_check_constraint('check_tone_score', 'qa_scores', 'tone_score >= 0 AND tone_score <= 100')
    op.add_column('tasks', sa.Column('org_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'organizations', ['org_id'], ['id'])
    op.add_column('users', sa.Column('org_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'org_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'org_id')
    op.drop_constraint('check_tone_score', 'qa_scores', type_='check')
    op.drop_constraint('check_resolution_score', 'qa_scores', type_='check')
    op.drop_constraint('check_overall_score', 'qa_scores', type_='check')
    op.drop_constraint('check_greeting_score', 'qa_scores', type_='check')
    op.drop_constraint('check_compliance_score', 'qa_scores', type_='check')
    op.alter_column('organizations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'mailbox_items', type_='foreignkey')
    op.drop_column('mailbox_items', 'org_id')
    op.add_column('calls', sa.Column('audio_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('calls', sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('calls', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_check_constraint(op.f('calls_status_check'), 'calls', "status = ANY (ARRAY['pending'::text, 'transcribing'::text, 'scoring'::text, 'scored'::text, 'failed'::text])")
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.create_foreign_key(op.f('calls_agent_id_fkey'), 'calls', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('calls_org_id_fkey'), 'calls', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_calls_org_date'), 'calls', ['org_id', 'call_date'], unique=False)
    op.alter_column('calls', 'call_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('calls', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('calls', 'audio_path')
    op.drop_column('calls', 'customer_ref')
    op.drop_constraint(None, 'background_tasks', type_='foreignkey')
    op.drop_column('background_tasks', 'org_id')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.create_foreign_key(op.f('agents_org_id_fkey'), 'agents', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'agents', type_='unique')
    op.alter_column('agents', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agents', 'email',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('agents', 'name',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('agents', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('agents', 'team')
    op.create_table('call_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('call_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('greeting_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('compliance_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('resolution_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('tone_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.NUMERIC(precision=5, scale=2), sa.Computed('((((greeting_score + compliance_score) + resolution_score) + tone_score) / (4)::numeric)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('flagged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('flag_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rubric_notes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('scored_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('compliance_score >= 0::numeric AND compliance_score <= 100::numeric', name=op.f('call_scores_compliance_score_check')),
    sa.CheckConstraint('greeting_score >= 0::numeric AND greeting_score <= 100::numeric', name=op.f('call_scores_greeting_score_check')),
    sa.CheckConstraint('resolution_score >= 0::numeric AND resolution_score <= 100::numeric', name=op.f('call_scores_resolution_score_check')),
    sa.CheckConstraint('tone_score >= 0::numeric AND tone_score <= 100::numeric', name=op.f('call_scores_tone_score_check')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('call_scores_call_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('call_scores_pkey')),
    sa.UniqueConstraint('call_id', name=op.f('call_scores_call_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_call_scores_call_id'), 'call_scores', ['call_id'], unique=False)
    # ### end Alembic commands ###
